/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{generation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generation */
        get: operations["get_generation_api_v1_generations__generation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{generation_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Generation */
        get: operations["download_generation_api_v1_generations__generation_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{generation_id}/export-attestation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Confirm Generation */
        put: operations["confirm_generation_api_v1_generations__generation_id__export_attestation_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{generation_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Generation */
        get: operations["preview_generation_api_v1_generations__generation_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_v1_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matters */
        get: operations["list_matters_api_v1_matters_get"];
        put?: never;
        /** Create Matter Route */
        post: operations["create_matter_route_api_v1_matters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters/{matter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Matter Route */
        get: operations["get_matter_route_api_v1_matters__matter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters/{matter_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document Route */
        post: operations["upload_document_route_api_v1_matters__matter_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters/{matter_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Facts Route */
        put: operations["save_facts_route_api_v1_matters__matter_id__facts_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters/{matter_id}/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Generation */
        post: operations["start_generation_api_v1_matters__matter_id__generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters/{matter_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Route */
        post: operations["validate_route_api_v1_matters__matter_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AmountComputationV1 */
        AmountComputationV1: {
            /**
             * Confirmation Status
             * @enum {string}
             */
            confirmation_status: "pending" | "confirmed" | "invalidated";
            /**
             * Formula Version
             * @default outstanding_amount_v1
             * @constant
             */
            formula_version: "outstanding_amount_v1";
            /** Input Revision */
            input_revision: number;
            /** Judgment Amount */
            judgment_amount: string;
            /** Paid Amount */
            paid_amount: string;
            /** Result */
            result: string;
            /**
             * Schema Version
             * @default amount_computation_v1
             * @constant
             */
            schema_version: "amount_computation_v1";
        };
        /** Body_upload_document_route_api_v1_matters__matter_id__documents_post */
        Body_upload_document_route_api_v1_matters__matter_id__documents_post: {
            /** Expected Revision */
            expected_revision: number;
            /** File */
            file: string;
            /** Kind */
            kind: string;
        };
        /** CapabilityResponse */
        CapabilityResponse: {
            /** Database */
            database: boolean;
            /** Docx */
            docx: boolean;
            /** Generation */
            generation: boolean;
            /** Image Ocr */
            image_ocr: boolean;
            /** Storage */
            storage: boolean;
            /**
             * Text Pdf
             * @default true
             */
            text_pdf: boolean;
            /** Worker */
            worker: boolean;
            /** Worker Reason */
            worker_reason?: ("worker_heartbeat_missing" | "worker_heartbeat_stale") | null;
        };
        /** CreateMatterRequest */
        CreateMatterRequest: {
            /** Eligibility Confirmed */
            eligibility_confirmed: boolean;
            /**
             * Eligibility Version
             * @default self_single_v1.0.0
             * @constant
             */
            eligibility_version: "self_single_v1.0.0";
        };
        /** ExportAttestationRequest */
        ExportAttestationRequest: {
            /**
             * Attestation Version
             * @default export_attestation_v1
             * @constant
             */
            attestation_version: "export_attestation_v1";
            /**
             * Critical Fields Reviewed
             * @constant
             */
            critical_fields_reviewed: true;
            /** Expected Revision */
            expected_revision: number;
            /**
             * Local Requirements Reviewed
             * @constant
             */
            local_requirements_reviewed: true;
            /**
             * Manual Review Understood
             * @constant
             */
            manual_review_understood: true;
        };
        /** GenerationResponse */
        GenerationResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Download Url */
            download_url: string | null;
            /** Export Attestation Version */
            export_attestation_version: string | null;
            /** Final Confirmed */
            final_confirmed: boolean;
            /** Final Confirmed At */
            final_confirmed_at: string | null;
            /** Id */
            id: string;
            /** Matter Id */
            matter_id: string;
            /** Preview Url */
            preview_url: string | null;
            /** Revision */
            revision: number;
            /** Sha256 */
            sha256: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "completed" | "superseded" | "failed";
        };
        /** GenerationStartResponse */
        GenerationStartResponse: {
            generation: components["schemas"]["GenerationResponse"];
            /** Job Id */
            job_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobResponse */
        JobResponse: {
            /** Attempt */
            attempt: number;
            /** Error Code */
            error_code: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "parse_document" | "generate_package";
            /** Max Attempts */
            max_attempts: number;
            /** Progress */
            progress: number | null;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Retryable */
            retryable: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "retry_scheduled" | "completed" | "failed_terminal";
        };
        /** MatterDocumentResponse */
        MatterDocumentResponse: {
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "legal_basis" | "applicant_id_front" | "applicant_id_back" | "respondent_id_front" | "respondent_id_back" | "performance_evidence";
            /** Parse Revision */
            parse_revision: number;
            /**
             * Parse Status
             * @enum {string}
             */
            parse_status: "pending" | "processing" | "completed" | "failed";
        };
        /** MatterResponse */
        MatterResponse: {
            amount_computation: components["schemas"]["AmountComputationV1"] | null;
            /** Confirmations */
            confirmations: {
                [key: string]: "pending" | "confirmed" | "invalidated";
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Title */
            display_title: string;
            /** Documents */
            documents: components["schemas"]["MatterDocumentResponse"][];
            /**
             * Dossier Schema Version
             * @constant
             */
            dossier_schema_version: "dossier_v2";
            /** Eligibility Confirmed */
            eligibility_confirmed: boolean;
            /** Eligibility Version */
            eligibility_version: string;
            /** Facts */
            facts: {
                [key: string]: string;
            };
            /** Generated Revision */
            generated_revision: number | null;
            /** Id */
            id: string;
            /** Latest Generation Id */
            latest_generation_id: string | null;
            /** Revision */
            revision: number;
            /** Scope Signals */
            scope_signals: components["schemas"]["ScopeSignalV1"][];
            /** Sources */
            sources: {
                [key: string]: components["schemas"]["SourceReferenceResponse"][];
            };
            /** Step Gates */
            step_gates: components["schemas"]["StepGateResponse"][];
            /**
             * Title State
             * @enum {string}
             */
            title_state: "pending_upload" | "processing" | "pending_confirmation" | "case_number_ready";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Validated Revision */
            validated_revision: number | null;
            /**
             * Workflow Profile
             * @constant
             */
            workflow_profile: "self_single_v1";
        };
        /** RevisionRequest */
        RevisionRequest: {
            /** Expected Revision */
            expected_revision: number;
        };
        /** SaveFactsRequest */
        SaveFactsRequest: {
            /** Confirm Fields */
            confirm_fields: string[];
            /** Dismissed Scope Signal Ids */
            dismissed_scope_signal_ids?: string[];
            /** Expected Revision */
            expected_revision: number;
            /** Fields */
            fields: {
                [key: string]: string;
            };
        };
        /** ScopeSignalV1 */
        ScopeSignalV1: {
            /**
             * Code
             * @enum {string}
             */
            code: "unsupported_multiple_applicants" | "unsupported_multiple_respondents" | "unsupported_representative" | "unsupported_organization_party" | "unsupported_multiple_obligations" | "unsupported_complex_obligation";
            /** Document Id */
            document_id: string;
            /** Id */
            id: string;
            /** Page */
            page?: number | null;
            /** Snippet */
            snippet: string;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "dismissed_as_parse_error";
        };
        /** SourceReferenceResponse */
        SourceReferenceResponse: {
            /** Confidence */
            confidence: number | null;
            /** Document Id */
            document_id: string;
            /**
             * Extraction Method
             * @enum {string}
             */
            extraction_method: "text" | "ocr" | "user" | "deterministic";
            /** Page */
            page: number | null;
            /** Parse Revision */
            parse_revision?: number | null;
            /** Snippet */
            snippet: string;
        };
        /** StepGateResponse */
        StepGateResponse: {
            /** Allowed */
            allowed: boolean;
            /** Reasons */
            reasons?: string[];
            /**
             * State
             * @enum {string}
             */
            state: "available" | "locked" | "complete" | "blocked";
            /**
             * Step
             * @enum {string}
             */
            step: "parties_and_basis" | "application" | "review" | "export";
        };
        /** UploadResponse */
        UploadResponse: {
            document: components["schemas"]["MatterDocumentResponse"];
            /** Job Id */
            job_id: string;
            /** Revision */
            revision: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssueResponse */
        ValidationIssueResponse: {
            /** Code */
            code: string;
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "blocking" | "warning" | "info";
        };
        /** ValidationResponse */
        ValidationResponse: {
            /** Blocking Count */
            blocking_count: number;
            /** Issues */
            issues: components["schemas"]["ValidationIssueResponse"][];
            /** Matter Id */
            matter_id: string;
            /** Revision */
            revision: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityResponse"];
                };
            };
        };
    };
    get_generation_api_v1_generations__generation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_generation_api_v1_generations__generation_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_generation_api_v1_generations__generation_id__export_attestation_put: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportAttestationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_generation_api_v1_generations__generation_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_v1_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matters_api_v1_matters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterResponse"][];
                };
            };
        };
    };
    create_matter_route_api_v1_matters_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMatterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_matter_route_api_v1_matters__matter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_route_api_v1_matters__matter_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_route_api_v1_matters__matter_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_facts_route_api_v1_matters__matter_id__facts_put: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveFactsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_generation_api_v1_matters__matter_id__generations_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_route_api_v1_matters__matter_id__validate_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
